#!/bin/bash
## Black        0;30     Dark Gray     1;30
## Red          0;31     Light Red     1;31
## Green        0;32     Light Green   1;32
## Brown/Orange 0;33     Yellow        1;33
## Blue         0;34     Light Blue    1;34
## Purple       0;35     Light Purple  1;35
## Cyan         0;36     Light Cyan    1;36
## Light Gray   0;37     White         1;37
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
GRAY='\033[1;30m'
NC='\033[0m' # No Color

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
my_software_conf="${DIR}/my-software.conf"
# software_conf=software.conf

get_new_version () {
  if [[ -z $2 ]]; then
    return
  fi
  echo
  echo $1
  url=$2
  html="`wget -qO- ${url}`"

  version=$(
    <<< "${html}" \
    grep -P -o -e "$3"|
    head -n 1
  )
  if [ "$4" = "$version" ]; then
    echo -e "... ${GREEN}up to date${NC}."
  else
    echo -e "... ${ORANGE}updated${NC}${GRAY}. New version: ${NC}${version}"
  fi
}

get_param() {
  line=$( grep $2 <<< "$1" )
  echo ${line##*|}
}

for uuid_version in $( egrep -v '^#|^$' ${my_software_conf:-${DIR}/my-software.conf.example} )
do
  uuid=${uuid_version%|*}
  version=${uuid_version#*|}
  params=$( grep "${uuid}" ${software_conf:-${DIR}/software.conf} )
  name=$( get_param "$params" 'name' )
  descr=$( get_param "$params" 'descr')
  url=$( get_param "$params" 'url')
  token=$( get_param "$params" 'token')
  get_new_version "$name ($descr)" "$url" "$token" "$version"
done
