#!/bin/bash

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

# <p><strong><small>YUMI MD5: 519A22DB3B9C3C31EBAF836DA936E959</small></strong></p>
# <div id="button"><a href="/downloads/YUMI/YUMI-2.0.6.9.exe" target="_blank" rel="noopener noreferrer"><noscript><img title="Download YUMI-2.0.6.9.exe" src="/wp-content/uploads/yumi-download.png" alt="Download YUMI-2.0.6.9.exe for Windows" /></noscript><img class="lazyload" title="Download YUMI-2.0.6.9.exe" src='data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20%20%22%3E%3C/svg%3E' data-src="/wp-content/uploads/yumi-download.png" alt="Download YUMI-2.0.6.9.exe for Windows" /><span style="position: absolute; top: 43px; left: 90px; padding: 0; margin: 0; color: #4a4a4a; font-size:12px;">YUMI-2.0.6.9.exe</span></a><small><span class="source" style="float: right; padding-top: 30px;"><a title="Source Code for YUMI-2.0.6.9.exe" target="_blank" rel="noopener noreferrer" href="/downloads/YUMI/YUMI-2.0.6.9.src.zip">YUMI Source Code</a></span></small></div>
# <p><strong><small>YUMI UEFI MD5: EC1BC0CADA83D8F430BE45D63AADCDFB</small></strong></p>
# <div id="button"><a href="/downloads/YUMI/YUMI-UEFI-0.0.2.0.exe" target="_blank" rel="noopener noreferrer"><noscript><img title="Download YUMI UEFI" src="/wp-content/uploads/yumi-download.png" alt="Download YUMI-UEFI-0.0.2.0.exe" /></noscript><img class="lazyload" title="Download YUMI UEFI" src='data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20%20%22%3E%3C/svg%3E' data-src="/wp-content/uploads/yumi-download.png" alt="Download YUMI-UEFI-0.0.2.0.exe" /><span style="position: absolute; top: 43px; left: 90px; padding: 0; margin: 0; color: #4a4a4a; font-size:12px;">YUMI-UEFI-0.0.2.0.exe</span></a><small><span  class="source" style="float: right; padding-top: 30px;"><a title="YUMI UEFI BETA Source Code" target="_blank" rel="noopener noreferrer" href="/downloads/YUMI/YUMI-UEFI-0.0.2.0.src.zip">YUMI UEFI Source Code</a></span></small></div>

if [ "$1" = "UEFI" ]
then
  # html_src_pre="(?<=<p><strong><small>YUMI UEFI )(.*?)(?=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI UEFI)"
  html_src_md5="(?<=YUMI UEFI MD5: )(.*?)(?=<\/small><\/strong><\/p>)"
  html_src_filename="(?<=<div id=\"button\"><a href=\"\/downloads\/YUMI\/)(.*?)(?=\" target=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI UEFI)"
else
  # html_src_pre="(?<=<p><strong><small>YUMI )(.*?)(?=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI-)"
  html_src_md5="(?<=MD5: )(.*?)(?=<\/small><\/strong><\/p>)"
  html_src_filename="(?<=<div id=\"button\"><a href=\"\/downloads\/YUMI\/)(.*?)(?=\" target=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI-)"
fi
#echo "$html_src_md5"
#echo "$html_srv_filename"


download_yumi () {
  cd $download_dir
  download_url="https://www.pendrivelinux.com/downloads/YUMI/"
  md5sum -c yumi.md5
  if [ "$?" -ne 0 ]
  then
    rm $1
    wget "$download_url$1"
    md5sum -c "$1.md5"
    if  [ "$?" -ne 0 ]
    then
      echo "FAIL"
      rm $1
    fi
  fi
  cd -
}

get_md5 () {
  cd $download_dir
  url='https://www.pendrivelinux.com/yumi-multiboot-usb-creator/'
  html="`wget -qO- ${url}`"

  # md5=$(
  #   <<< "${html}" \
  #   grep -P -o -e "$html_src_pre" |
  #   grep -P -o -e "$html_src_md5" |
  #   head -n 1
  md5=$(
      <<< "${html}" \
      grep -P -o -e "$html_src_md5" |
      head -n 1
  )

  # filename=$(
  #   <<< "${html}" \
  #   grep -P -o -e "$html_src_pre" |
  #   grep -P -o -e "$html_src_filename" |
  #   head -n 1
  # )
  filename=$(
    <<< "${html}" \
    grep -P -o -e "$html_src_filename" |
    head -n 1
  )

  echo "${md5}  ${filename}" > ${filename}.md5
  cd -
}

get_md5
download_yumi $filename

# https://www.pendrivelinux.com/yumi-multiboot-usb-creator/
# https://www.pendrivelinux.com/downloads/YUMI/YUMI-2.0.5.8.exe
