#!/bin/bash

# PGP Public Key: https://www.idrix.fr/VeraCrypt/VeraCrypt_PGP_public_key.asc (ID=0x680D16DE, Fingerprint=5069A233D55A0EEB174A5FC3821ACD02680D16DE)

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

download_veracrypt () {
  cd $download_dir
  download_url="https://launchpad.net/veracrypt/trunk/$1$4/+download/"
  signture_exe_file="VeraCrypt $2 $1$3.exe.sig"
  signture_sha_file="veracrypt-$1$3-sha256sum.txt.sig"
  exe_file="VeraCrypt $2 $1$3.exe"
  sha_file="veracrypt-$1$3-sha256sum.txt"
  rm "$signture_exe_file"
  rm "$signture_sha_file"
  wget "$download_url$signture_exe_file"
  wget "$download_url$signture_sha_file"
  gpg --verify "$signture_sha_file" "$sha_file"
  if [ "$?" -ne 0 ]
  then
    rm "$sha_file"
    wget "$download_url$sha_file"
    gpg --verify "$signture_sha_file" "$sha_file"
    if  [ "$?" -ne 0 ]
    then
      echo "FAIL"
      rm "$sha_file"
    fi
  fi
  if [ -f "$exe_file" ]
  then
    head -n 10 "$sha_file" | tr -d '\r' | sha256sum --ignore-missing -c
    if  [ "$?" -ne 0 ]
    then
      rm "$exe_file"
    fi
  fi
  if [ ! -f "$exe_file" ]
  then
    wget "$download_url$exe_file"
  fi
  # finall pgp check
  gpg --verify "$signture_exe_file" "$exe_file"
  if  [ "$?" -ne 0 ]
  then
    echo "FAIL"
    rm "$exe_file"
  fi
  cd -
}

download_veracrypt 1.24 Setup -Hotfix1 -hotfix1
download_veracrypt 1.24 Portable -Hotfix1 -hotfix1

# https://launchpad.net/veracrypt/trunk/1.24-hotfix1/+download/veracrypt-1.24-Hotfix1-sha256sum.txt.sig
# https://launchpad.net/veracrypt/trunk/1.24-hotfix1/+download/veracrypt-1.24-Hotfix1-sha256sum.txt
# https://launchpad.net/veracrypt/trunk/1.24-hotfix1/+download/VeraCrypt%20Setup%201.24-Hotfix1.exe.sig
# https://launchpad.net/veracrypt/trunk/1.24-hotfix1/+download/VeraCrypt%20Setup%201.24-Hotfix1.exe
# https://launchpad.net/veracrypt/trunk/1.24-hotfix1/+download/VeraCrypt%20Portable%201.24-Hotfix1.exe.sig
# https://launchpad.net/veracrypt/trunk/1.24-hotfix1/+download/VeraCrypt%20Portable%201.24-Hotfix1.exe
