#!/bin/bash

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

download_npp () {
  cd $download_dir
  download_url="https://notepad-plus-plus.org/repository/$1/$2/"
  checksum_file="npp.$2.sha1.md5.digest.txt"
  exe_file="npp.$2.Installer.x64.exe"
  rm $checksum_file
  wget "$download_url$checksum_file"
  if [ -f $checksum_file ]
  then
    head -n 10 $checksum_file | tail -n 8 | tr -d '\r' | sed 's/  npp./npp./g' | sha1sum --ignore-missing -c
    if  [ "$?" -ne 0 ]
    then
      rm $exe_file
      wget "$download_url$exe_file"
      head -n 10 $checksum_file | tail -n 8 | tr -d '\r' | sed 's/  npp./npp./g' | sha1sum --ignore-missing -c
      if  [ "$?" -ne 0 ]
      then
        echo "FAIL"
        rm $exe_file
      fi
    fi
  fi
  cd -
}

download_npp 7.x 7.6.2

#https://notepad-plus-plus.org/repository/7.x/7.5.9/npp.7.5.9.sha1.md5.digest.txt
#https://notepad-plus-plus.org/repository/7.x/7.5.9/npp.7.5.9.Installer.x64.exe
