#!/bin/bash

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

download_npp () {
  cd "$download_dir" || return
  download_url="http://download.notepad-plus-plus.org/repository/$1/$2/"
  signture_file="npp.$2.Installer.x64.exe.sig"
  exe_file="npp.$2.Installer.x64.exe"
  rm "$signture_file"
  wget "$download_url$signture_file"
  if [ -f "$signture_file" ]
  then
    if ! gpg --verify "$signture_file" "$exe_file"
    then
      rm "$exe_file"
      wget "$download_url$exe_file"
      if ! gpg --verify "$signture_file" "$exe_file"
      then
        echo "FAIL"
        rm "$exe_file"
      fi
    fi
  fi
  cd - || return
}

download_npp 7.x 7.8.5

#http://download.notepad-plus-plus.org/repository/7.x/7.8/npp.7.8.Installer.x64.exe
#http://download.notepad-plus-plus.org/repository/7.x/7.8/npp.7.8.Installer.x64.exe.sig
#https://notepad-plus-plus.org/gpg/nppGpgPub.asc
