#!/bin/bash

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

# <p><strong><small>YUMI MD5: 606FC194804379C1B2B8001F6F176C66</small></strong></p><div id="button"><a href="/downloads/YUMI/YUMI-2.0.6.6.exe" target="_blank" rel="noopener noreferrer"><noscript><img title="Download YUMI-2.0.6.6.exe"
# <p><strong><small>YUMI UEFI MD5: 67C03CD41ADAEF03DD4E90DF6004B40E</small></strong></p><div id="button"><a href="/downloads/YUMI/YUMI-UEFI-0.0.1.6.exe" target="_blank" rel="noopener noreferrer"><noscript><img title="Download YUMI UEFI"

if [ "$1" = "UEFI" ]
then
  html_src_pre="(?<=<p><strong><small>YUMI UEFI )(.*?)(?=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI UEFI)"
  html_src_md5="(?<=MD5: )(.*?)(?=<\/small><\/strong><\/p>)"
  html_src_filename="(?<=<div id=\"button\"><a href=\"\/downloads\/YUMI\/)(.*?)(?=\" target=)"
else
  html_src_pre="(?<=<p><strong><small>YUMI )(.*?)(?=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI-)"
  html_src_md5="(?<=MD5: )(.*?)(?=<\/small><\/strong><\/p>)"
  html_src_filename="(?<=<div id=\"button\"><a href=\"\/downloads\/YUMI\/)(.*?)(?=\" target=)"
fi
#echo "$html_src_md5"
#echo "$html_srv_filename"


download_yumi () {
  cd $download_dir
  download_url="https://www.pendrivelinux.com/downloads/YUMI/"
  md5sum -c yumi.md5
  if [ "$?" -ne 0 ]
  then
    rm $1
    wget "$download_url$1"
    md5sum -c "$1.md5"
    if  [ "$?" -ne 0 ]
    then
      echo "FAIL"
      rm $1
    fi
  fi
  cd -
}

get_md5 () {
  cd $download_dir
  url='https://www.pendrivelinux.com/yumi-multiboot-usb-creator/'
  html="`wget -qO- ${url}`"

  md5=$(
    <<< "${html}" \
    grep -P -o -e "$html_src_pre" |
    grep -P -o -e "$html_src_md5" |
    head -n 1
  )

  filename=$(
    <<< "${html}" \
    grep -P -o -e "$html_src_pre" |
    grep -P -o -e "$html_src_filename" |
    head -n 1
  )

  echo "${md5}  ${filename}" > ${filename}.md5
  cd -
}

get_md5
download_yumi $filename

# https://www.pendrivelinux.com/yumi-multiboot-usb-creator/
# https://www.pendrivelinux.com/downloads/YUMI/YUMI-2.0.5.8.exe
