#!/bin/bash

##Add gparted keys:
#gpg --recv-keys 8e94c9cd163e3fb0

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

download_gparted () {
  cd $download_dir
  download_url="https://gparted.org/gparted-live/stable/"
  download_iso_url="https://downloads.sourceforge.net/gparted/"
  signture_file="CHECKSUMS.TXT.gpg"
  checksum_file="CHECKSUMS.TXT"
  rm $signture_file
  wget "$download_url$signture_file"
  gpg --verify $signture_file $checksum_file
  if [ "$?" -ne 0 ]
  then
    rm $checksum_file
    wget "$download_url$checksum_file"
    gpg --verify $signture_file $checksum_file
    if  [ "$?" -ne 0 ]
    then
      echo "FAIL"
      rm $checksum_file
    fi
  fi
  if [ -f $checksum_file ]
  then
    rm $1
    wget "$download_iso_url$1"
    sha512sum --ignore-missing -c CHECKSUMS.TXT
    if  [ "$?" -ne 0 ]
    then
      echo "FAIL"
      rm $1
    fi
  fi
  cd -
}

download_gparted gparted-live-0.33.0-2-i686.iso
download_gparted gparted-live-0.33.0-2-amd64.iso

#https://gparted.org/gparted-live/stable/CHECKSUMS.TXT.gpg
#https://gparted.org/gparted-live/stable/CHECKSUMS.TXT
#https://downloads.sourceforge.net/gparted/gparted-live-0.32.0-1-i686.iso
#https://downloads.sourceforge.net/gparted/gparted-live-0.32.0-1-amd64.iso
