#!/bin/bash

if [ "$DOWNLOADS" = "" ]
then
  download_dir=~/Downloads
else
  download_dir=$DOWNLOADS
fi
#echo $download_dir

# <p><strong><small>YUMI MD5: 9EA60C10BC6A056A52B044BBEB56C7F4</small></strong></p>
# <div id="button"><a href="/downloads/YUMI/YUMI-2.0.7.8.exe" rel="noopener"><span style="position: absolute; top: 43px; left: 90px; padding: 0; margin: 0; color: #4a4a4a; font-size: 12px;">YUMI-2.0.7.8.exe</span></a><a href="/downloads/YUMI/YUMI-2.0.7.8.exe" rel="noopener"><img loading="lazy" class="alignnone" title="Download YUMI-2.0.7.8.exe" src="/wp-content/uploads/yumi-download.png" alt="Download YUMI-2.0.7.8.exe for Windows" width="232" height="61" /></a><small><span class="source" style="float: right; padding-top: 30px;"><a title="Source Code for YUMI-2.0.7.8.exe" href="/downloads/YUMI/YUMI-2.0.7.8.src.zip" rel="noopener">YUMI Source Code</a></span></small></div>
# <p><strong><small>YUMI UEFI MD5: C835597A8710C198DB5EA6FD58AD60FD</small></strong></p>
# <div id="button"><a href="/downloads/YUMI/YUMI-UEFI-0.0.2.8.exe" rel="noopener"><span style="position: absolute; top: 43px; left: 90px; padding: 0; margin: 0; color: #4a4a4a; font-size: 12px;">YUMI-UEFI-0.0.2.8.exe</span></a><a href="/downloads/YUMI/YUMI-UEFI-0.0.2.8.exe" rel="noopener"><img loading="lazy" class="alignnone" title="Download YUMI UEFI" src="/wp-content/uploads/uefi-yumi-download.png" alt="Download YUMI-UEFI-0.0.2.8.exe" width="232" height="61" /></a><small><span class="source" style="float: right; padding-top: 30px;"><a title="YUMI UEFI BETA Source Code" href="/downloads/YUMI/YUMI-UEFI-0.0.2.8.src.zip" rel="noopener">YUMI UEFI Source Code</a></span></small></div>

if [ "$1" = "UEFI" ]
then
  # html_src_pre="(?<=<p><strong><small>YUMI UEFI )(.*?)(?=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI UEFI)"
  html_src_md5="(?<=YUMI UEFI MD5: )(.*?)(?=<\/small><\/strong><\/p>)"
  html_src_filename="(?<=<\/span><\/a><a href=\"\/downloads\/YUMI\/)(.*?)(?=\" rel=\"noopener\"><img loading=\"lazy\" class=\"alignnone\" title=\"Download YUMI UEFI)"
else
  # html_src_pre="(?<=<p><strong><small>YUMI )(.*?)(?=\"_blank\" rel=\"noopener noreferrer\"><noscript><img title=\"Download YUMI-)"
  html_src_md5="(?<=MD5: )(.*?)(?=<\/small><\/strong><\/p>)"
  html_src_filename="(?<=<\/span><\/a><a href=\"\/downloads\/YUMI\/)(.*?)(?=\" rel=\"noopener\"><img loading=\"lazy\" class=\"alignnone\" title=\"Download YUMI-)"
fi
#echo "$html_src_md5"
#echo "$html_srv_filename"


download_yumi () {
  cd "$download_dir" || return
  download_url="https://www.pendrivelinux.com/downloads/YUMI/"
  if ! md5sum -c yumi.md5
  then
    rm "$1"
    wget "$download_url$1"
    if ! md5sum -c "$1.md5"
    then
      echo "FAIL"
      rm "$1"
    fi
  fi
  cd - || return
}

get_md5 () {
  cd "$download_dir" || return
  url='https://www.pendrivelinux.com/yumi-multiboot-usb-creator/'
  html="$(wget -qO- ${url})"

  # md5=$(
  #   <<< "${html}" \
  #   grep -P -o -e "$html_src_pre" |
  #   grep -P -o -e "$html_src_md5" |
  #   head -n 1
  md5=$(
      <<< "${html}" \
      grep -P -o -e "$html_src_md5" |
      head -n 1
  )

  # filename=$(
  #   <<< "${html}" \
  #   grep -P -o -e "$html_src_pre" |
  #   grep -P -o -e "$html_src_filename" |
  #   head -n 1
  # )
  filename=$(
    <<< "${html}" \
    grep -P -o -e "$html_src_filename" |
    head -n 1
  )

  echo "${md5}  ${filename}" > "${filename}".md5
  cd - || return
}

get_md5
download_yumi "$filename"

# https://www.pendrivelinux.com/yumi-multiboot-usb-creator/
# https://www.pendrivelinux.com/downloads/YUMI/YUMI-2.0.5.8.exe
